addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"         % "1.1.2")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"              % "1.16.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalajs-bundler"      % "0.21.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"             % "0.11.0")
addSbtPlugin("org.portable-scala"  % "sbt-scalajs-crossproject" % "1.3.2")
